services: # something missing???
  app:
        container_name: app
        build: .
        command: nodemon --watch /usr/src/app -e js app.js
        ports:
          - "3000:3000"
        volumes:
          - ./app:/usr/src/app
        depends_on:
          - mongo
        environment:
          JWT_SECRET: "miciomicio"
  mongo:
        container_name: mongo
        image: mongo
        volumes:
          - ./data:/data/db
          - ./mongo-init:/docker-entrypoint-initdb.d
        ports:
          - "27017:27017"
